project_settings:
  default_crs: "EPSG:4326"
  data_path: "data/raw"
  output_path: "outputs"

data_processing:
  buffer_distance: 100
  simplify_tolerance: 0.01

visualization:
  map_style: "open-street-map"
  color_scale: "Viridis"
  default_width: 1000
  default_height: 600