data_paths:
  raw: data/raw/
  processed: data/processed/
  external: data/external/

output_paths:
  maps: outputs/maps/
  reports: outputs/reports/
  models: outputs/models/

project_settings:
  default_crs: EPSG:4326
  coordinate_precision: 6
  date_format: "%Y-%m-%d"

api_keys:
  mapbox_token: ${MAPBOX_TOKEN}
  google_maps_key: ${GOOGLE_MAPS_KEY}